---
- name: KUBE-DASH | Assures {{ kube_addons_dir }}/kube-dash dir exists
  file: path={{ kube_addons_dir }}/kube-dash state=directory

- name: KUBE-DASH | Download kube-dash files from Kubernetes repo
  get_url:
    url=https://raw.githubusercontent.com/indigo-dc/kubernetes/master/ha-kubernetes/ansible/roles/kubernetes-addons/files/kube-dash/{{ item }}
    dest="{{ kube_addons_dir }}/kube-dash/"
    force=yes
    validate_certs=False
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
    no_proxy: "{{ no_proxy|default('') }}"
  with_items:
    - kube-dash-rc.yaml
    - kube-dash-svc.yaml
