---
- name: KUBE-UI | Assures {{ kube_addons_dir }}/kube-ui dir exists
  file: path={{ kube_addons_dir }}/kube-ui state=directory

- name: KUBE-UI | Download kube-ui files from Kubernetes repo
  get_url:
    url=https://github.com/indigo-dc/kubernetes/tree/master/ha-kubernetes/ansible/roles/kubernetes-addons/files/kube-ui/{{ item }}
    dest="{{ kube_addons_dir }}/kube-ui/"
    force=yes
    validate_certs=False
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
    no_proxy: "{{ no_proxy|default('') }}"
  with_items:
    - dashboard-controller.yaml
    - dashboard-service.yaml
