apiVersion: v1
kind: ReplicationController
metadata:
  name: service-loadbalancer
  namespace: kube-system
  labels:
    app: service-loadbalancer
    version: v1
spec:
  replicas: 2
  selector:
    app: service-loadbalancer
    version: v1
  template:
    metadata:
      labels:
        app: service-loadbalancer
        version: v1
    spec:
      nodeSelector:
        role: loadbalancer
      volumes:
      - name: config-vol
        hostPath:
          path: /srv/kubernetes/
      - name: ssl-vol
        hostPath:
          path: /etc/nginx/ssl/
      containers:
      - image: gcr.io/google_containers/servicelb:0.4
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: haproxy
        ports:
        # All http services
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        # ssl term
        - containerPort: 443
          hostPort: 443
          protocol: TCP
        # haproxy stats
        - containerPort: 1936
          hostPort: 1936
          protocol: TCP
        # haproxy mysql
        - containerPort: 3306
          hostPort: 3306
          protocol: TCP
        resources: {}
        args:
        - --use-kubernetes-cluster-service=true
        - --ssl-cert=/etc/nginx/ssl/nginx.pem
        - --tcp-services=mysql:3306,nginxhttps:443
        volumeMounts:
        - mountPath: /etc/nginx/ssl/
          name: ssl-vol
        - mountPath: /srv/kubernetes/
          name: config-vol
        env:
        - name: KUBECONFIG
          value: /srv/kubernetes/kubeconfig.yaml
      imagePullSecrets:
        - name: nginxsecret
