---
- name: Install keepalived
  action: "{{ ansible_pkg_mgr }} name=keepalived state=present"

- name: Enable and start keepalived
  service:
    name: keepalived
    state: started
    enabled: yes
  register: start_result

- set_fact:
    haproxy_start_result_changed: "{{ start_result | changed }}"
