---
- name: Install keepalived
  action: "{{ ansible_pkg_mgr }} name=keepalived state=present"

- name: Configure haproxy
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644

- name: Enable and start keepalived
  service:
    name: keepalived
    state: started
    enabled: yes
  register: start_result

- set_fact:
    haproxy_start_result_changed: "{{ start_result | changed }}"
